[package]
name = "da-engine"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
da-gguf = { path = "../da-gguf" }
da-kernels = { path = "../da-kernels" }
da-graph = { path = "../da-graph" }
thiserror.workspace = true
rayon.workspace = true

[dev-dependencies]
da-parity = { path = "../../da-parity" }
